server:
  port: 8091

feign:
  circuitbreaker:
    enabled: true

spring:
  h2:
    console:
      enabled: true
  # ===============================
  # DB
  # ===============================
  datasource:
    url: jdbc:h2:mem:easyjobsaccountsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: root
    password: admin

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

Feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: "*"
management:
  endpoint:
    web:
      exposure:
        include: "*"
