server:
  port: 8079

eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-3-92-61-60.compute-1.amazonaws.com:8099/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Accounts
          uri: lb://accounts
          predicates:
            - Path=/accounts/**
        - id: Appointment
          uri: lb://Appointment
          predicates:
            - Path=/Appointment/**
        - id: Qualification
          uri: lb://Qualification
          predicates:
            - Path=/Qualification/**
        - id: TechnicianSearch
          uri: lb://technicianSearch
          predicates:
            - Path=/technicianSearch/**
        - id: CloseAppointment
          uri: lb://AppointmentHistories
          predicates:
            - Path=/AppointmentHistories/**
        - id: TechnicianDetails
          uri: lb://TechnicianDetails
          predicates:
            - Path=/TechnicianDetails/**