server:
  port: 8079

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Accounts
          uri: lb://accounts
          predicates:
            - Path=/accounts/**
        - id: Appointment
          uri: lb://Appointment
          predicates:
            - Path=/Appointment/**
        - id: Qualification
          uri: lb://Qualification
          predicates:
            - Path=/Qualification/**
        - id: TechnicianSearch
          uri: lb://technicianSearch
          predicates:
            - Path=/technicianSearch/**
        - id: AppointmentHistory
          uri: lb://CloseAppointment
          predicates:
            - Path=/CloseAppointment/**
        - id: TechnicianDetails
          uri: lb://TechnicianDetail
          predicates:
            - Path=/TechnicianDetail/**